const notes: Record<number, string> = {
  7: 'Văn Miếu Môn là cổng chính của khu Văn Miếu và có hai tầng. Tầng trên tạo dáng bề thế, tầng dưới là lối đi vào khu di tích.',
  8: 'Đôi rồng đá phía trước cổng Văn Miếu mang phong cách nghệ thuật thời Lê, gắn với giai đoạn Nho học và khoa cử phát triển mạnh.',
  9: 'Đôi rồng đá phía sau cổng mang phong cách thời Nguyễn, cho thấy di tích được bổ sung và tu sửa qua nhiều triều đại.',
  12: 'Học trò học tập tại Quốc Tử Giám được gọi là giám sinh. Đây là những người theo học tại cơ sở giáo dục cao nhất của triều đình.',
  14: 'Hồ Văn nằm phía trước khu Văn Miếu. Không gian này từng gắn với các hoạt động thưởng ngoạn và bình thơ của giới nho sĩ.',
  15: 'Kim Châu là gò đất nằm giữa Hồ Văn. Đây là một điểm nhấn cảnh quan trong không gian phía trước Văn Miếu.',
  16: 'Hai cổng nhỏ ở hai bên cổng Đại Trung là Thành Đức và Đạt Tài. Tên gọi thể hiện quan niệm tu dưỡng đức hạnh và tài năng.',
  17: 'Khuê Văn Các được chọn làm biểu tượng của Hà Nội nhờ hình dáng đặc trưng và giá trị văn hóa gắn với truyền thống hiếu học.',
  19: 'Khuê Văn Các được xây dựng năm 1805 dưới thời Tổng trấn Bắc Thành Nguyễn Văn Thành.',
  21: 'Khuê Văn Các được sơn màu đỏ, tạo điểm nhấn nổi bật giữa không gian cây xanh và các công trình cổ của Văn Miếu.',
  22: 'Hai cổng nhỏ hai bên Khuê Văn Các là Bí Văn và Súc Văn. Tên gọi gợi đến việc tích lũy tri thức và trau dồi văn chương.',
  26: '82 bia hiện còn ghi họ tên và quê quán của 1.304 tiến sĩ. Các tấm bia là nguồn tư liệu quan trọng về lịch sử khoa cử Việt Nam.',
  27: 'Vua Lê Thánh Tông là người cho khởi dựng bia tiến sĩ từ năm 1484 để tôn vinh hiền tài và khuyến khích việc học.',
  29: 'Khoa thi năm 1442 là khoa thi đầu tiên được dựng bia. Đây là mốc mở đầu cho hệ thống bia tiến sĩ còn lưu lại tại Văn Miếu.',
  30: 'Khoa thi năm 1779 là khoa thi cuối cùng được dựng bia trong hệ thống 82 bia tiến sĩ tại Văn Miếu.',
  31: 'Khoa thi có số người đỗ nhiều nhất lấy đỗ 62 người. Con số này cho thấy quy mô tuyển chọn thay đổi tùy từng khoa thi.',
  32: 'Khoa thi có số người đỗ ít nhất chỉ có 3 người. Kết quả mỗi khoa thi phụ thuộc vào tiêu chuẩn và chất lượng bài thi.',
  33: 'Bia tiến sĩ được làm bằng đá xanh, một vật liệu bền giúp lưu giữ tên tuổi và thông tin khoa cử qua nhiều thế kỷ.',
  34: 'Đá xanh dùng dựng bia được khai thác ở Thanh Hóa, sau đó vận chuyển về kinh đô để chế tác.',
  35: 'Nội dung trên bia được khắc bằng chữ Hán, là loại chữ được sử dụng trong hành chính, giáo dục và khoa cử thời đó.',
  36: 'Ngoài họ tên và quê quán, bia còn khắc bài ký. Bài ký ghi lại hoàn cảnh khoa thi và tư tưởng đề cao việc dùng người tài.',
  37: 'Giếng nằm giữa vườn bia có tên Thiên Quang Tỉnh, thường gọi là giếng Thiên Quang.',
  38: 'Giếng Thiên Quang nằm ở giữa vườn bia tiến sĩ, tạo trục cảnh quan cân đối giữa các dãy bia hai bên.',
  39: 'Giếng Thiên Quang có hình vuông. Hình dáng này là một nét đặc trưng dễ nhận biết của khu vườn bia.',
  40: 'Năm 1075, triều Lý tổ chức khoa thi Nho học đầu tiên trong lịch sử khoa cử Việt Nam.',
  41: 'Vua Lý Nhân Tông cho tổ chức khoa thi đầu tiên vào năm 1075 để tuyển chọn người có kiến thức phục vụ đất nước.',
  43: 'Lý Nhân Tông là con của vua Lý Thánh Tông. Ông lên ngôi khi còn nhỏ nhưng về sau có nhiều đóng góp cho giáo dục và khoa cử.',
  44: 'Thi Hương là kỳ thi đầu tiên trong hệ thống thi cử. Người đỗ mới có thể tiếp tục tham dự các kỳ thi cao hơn.',
  45: 'Thi Hội được tổ chức sau Thi Hương tại kinh đô, nhằm tuyển chọn những người đủ năng lực dự kỳ thi Đình.',
  46: 'Thi Đình là kỳ thi cuối cùng, được tổ chức tại cung điện và do nhà vua hoặc triều đình chủ trì.',
  47: 'Ba danh hiệu cao nhất là Trạng nguyên, Bảng nhãn và Thám hoa. Ba người đứng đầu được gọi chung là Tam khôi.',
  49: 'Quách Đồng Dần được ghi nhận là người đỗ tiến sĩ ở tuổi 68, cho thấy khoa cử thời xưa không chỉ dành cho người trẻ.',
  51: 'Nguyễn Hiền đỗ Trạng nguyên khi mới 13 tuổi, thường được nhắc đến như vị Trạng nguyên trẻ nhất lịch sử khoa cử Việt Nam.',
  52: 'Tiến sĩ được phân thành ba hạng. Cách phân hạng giúp triều đình xác định thứ bậc và việc bổ dụng sau kỳ thi.',
  53: 'Trạng nguyên là danh hiệu cao nhất trong các kỳ thi tiến sĩ, dành cho người đứng đầu bảng vàng.',
  54: 'Người đứng đầu cả Thi Hương, Thi Hội và Thi Đình được gọi là Tam nguyên, nghĩa là đứng đầu ở cả ba cấp thi.',
  56: 'Dưới thời Lê, người đỗ bốn kỳ của khoa thi Hương được gọi là Hương cống.',
  57: 'Dưới thời Lê, người trúng ba kỳ của khoa thi Hương được gọi là Sinh đồ.',
  58: 'Tên gọi Cử nhân được dùng cho người đỗ kỳ thi Hương dưới triều Nguyễn.',
  59: 'Kinh nghĩa là bài thi yêu cầu thí sinh giải thích kinh điển Nho giáo, qua đó thể hiện khả năng hiểu và vận dụng lời kinh.',
  60: 'Dưới thời Nguyễn, người trúng ba kỳ thi Hương được gọi là Tú tài.',
  61: 'Người đứng đầu kỳ thi Hương được gọi là Giải nguyên.',
  62: 'Người đứng đầu kỳ thi Hội được gọi là Hội nguyên.',
  63: 'Người đứng đầu kỳ thi Đình được gọi là Đình nguyên.',
  64: 'Thi Hội được tổ chức tại kinh đô, nơi triều đình tập trung việc tuyển chọn nhân tài cấp quốc gia.',
  65: 'Thi Đình chỉ có một kỳ. Đây là vòng thi cuối để xếp hạng những người đã vượt qua các kỳ trước.',
  66: 'Nhà vua là người hỏi thi trong kỳ thi Đình. Điều này thể hiện tầm quan trọng của kỳ thi đối với triều đình.',
  67: 'Khoa thi năm 1640 có số sĩ tử tham gia đông nhất, khoảng 6.000 người.',
  68: 'Trịnh Thiết Trường và Nguyễn Nguyên Chẩn là hai thầy trò cùng đỗ trong khoa thi năm 1442.',
  69: 'Ngô Trí Tri và Ngô Trí Hòa là hai cha con cùng đỗ tiến sĩ trong một khoa thi.',
  70: 'Khoa thi năm 1592 ghi nhận trường hợp hai cha con cùng thi đỗ tiến sĩ.',
  71: 'Lương Như Hộc được xem là ông tổ nghề in mộc bản của nước ta. Ông đỗ tiến sĩ trong khoa thi năm 1442.',
  72: 'Ngô Sĩ Liên là một trong những người biên soạn Đại Việt sử ký toàn thư, bộ chính sử quan trọng của Việt Nam.',
  73: 'Lương Thế Vinh đỗ Trạng nguyên khoa thi năm 1463 và nổi tiếng về toán học, nên được dân gian gọi là Trạng Lường.',
  76: 'Ngô Thì Nhậm có vai trò quan trọng trong việc giúp vua Quang Trung đánh quân Thanh, trong đó có chiến thắng Ngọc Hồi – Đống Đa.',
  77: 'Nguyễn Trực được xem là vị Trạng nguyên đầu tiên được khắc tên trên bia tiến sĩ tại Văn Miếu – Quốc Tử Giám Thăng Long.',
  78: 'Phan Huy Ôn là vị tiến sĩ cuối cùng được khắc tên trên bia tại Văn Miếu – Quốc Tử Giám Hà Nội.',
  79: 'Nguyễn Khuyến quê ở Yên Đỗ và đạt danh hiệu Tam nguyên. Tên ông được đặt cho một tuyến phố ở Hà Nội.',
  80: 'Theo thống kê thường được sử dụng trong bộ câu hỏi, lịch sử khoa cử Việt Nam có 46 người đạt danh hiệu Trạng nguyên.',
  81: 'Trong số các tiến sĩ được khắc tên trên bia, có 18 người đạt danh hiệu Trạng nguyên.',
  82: 'Lương Như Hộc đỗ Thám hoa trong khoa thi năm 1442, trước khi được biết đến với đóng góp cho nghề in mộc bản.',
  83: 'Tế Tửu là chức vụ đứng đầu Quốc Tử Giám. Phùng Khắc Khoan từng giữ chức vụ này.',
  84: 'Ngô Thì Sĩ và Ngô Thì Nhậm là hai cha con cùng đỗ tiến sĩ và cùng làm quan dưới triều Lê.',
  86: 'Lê Quý Đôn đỗ Bảng nhãn trong khoa thi năm 1752, một thành tích cao trong hệ thống khoa cử thời Lê.',
  87: 'Tư nghiệp là chức vụ quản lý và giảng dạy tại Quốc Tử Giám. Lê Quý Đôn từng đảm nhiệm chức vụ này.',
  88: 'Ngô Sĩ Liên là một trong những soạn giả của Đại Việt sử ký toàn thư, bộ chính sử ghi chép lịch sử Đại Việt.',
  89: 'Ngô Sĩ Liên từng giữ chức Tư nghiệp ở Quốc Tử Giám, bên cạnh công việc biên soạn sử sách.',
  90: 'Nguyễn Nghiễm từng giữ chức Tế Tửu, chức vụ cao nhất tại Quốc Tử Giám.',
  91: 'Lễ xướng danh được tổ chức trong sân rồng, nơi triều đình công bố và vinh danh những người đỗ đạt.',
  92: 'Người đỗ tiến sĩ được ban mũ, áo và đai. Đây là những vật phẩm thể hiện sự vinh danh của triều đình.',
  93: 'Người đỗ tiến sĩ được ban yến tiệc ở vườn Quỳnh Lâm, một nghi lễ vinh danh người đỗ đạt.',
  94: 'Người đỗ Tam khôi được vua cho đi chơi phố ba ngày, một hình thức chúc mừng đặc biệt sau khi đỗ đạt.',
  95: 'Dưới triều Mạc có một khoa thi được dựng bia tiến sĩ tại Văn Miếu – Quốc Tử Giám.',
  96: 'Triều Nguyễn tổ chức 39 khoa thi tiến sĩ theo thống kê dùng trong bộ câu hỏi.',
  97: 'Cổng Đại Thành có ba gian, phù hợp với kết cấu nghi lễ của khu vực Đại Thành.',
  98: 'Điện Đại Thành lợp ngói mũi hài, loại ngói truyền thống thường thấy trong kiến trúc cổ Việt Nam.',
  99: 'Trên nóc nhà Bái Đường có hình Lưỡng long chầu nguyệt, hai rồng hướng về mặt trăng – biểu tượng quen thuộc trong kiến trúc truyền thống.',
  100: 'Sân Đại Bái được lát bằng gạch Bát Tràng, loại gạch truyền thống nổi tiếng của vùng Bát Tràng.',
  101: 'Tòa Bái Đường có chín gian, tạo nên không gian rộng cho các hoạt động thờ tự và nghi lễ.',
  102: 'Điện Đại Thành thờ Khổng Tử cùng các học trò và tiên hiền Nho học, phù hợp với chức năng của Văn Miếu.',
  103: 'Khổng Tử sinh tại nước Lỗ, thuộc lãnh thổ Trung Quốc ngày nay. Ông là nhân vật nền tảng của Nho học.',
  104: 'Khổng Tử được xem là người đặt nền tảng cho Nho giáo, hệ tư tưởng ảnh hưởng sâu rộng đến giáo dục và quản trị ở Đông Á.',
  105: 'Bốn vị được phối thờ với Khổng Tử là các học trò tiêu biểu của ông, thể hiện truyền thống tôn sư trọng đạo.',
  106: 'Mạnh Tử là một nhà tư tưởng Trung Quốc và là người kế thừa, phát triển tư tưởng Nho học.',
  107: 'Câu chuyện Mạnh mẫu tam thiên kể rằng mẹ Mạnh Tử ba lần chuyển nhà để tạo môi trường tốt cho con học tập.',
  108: 'Tượng Mạnh Tử tại điện Đại Thành được làm bằng gỗ, một chất liệu thường được sử dụng để tạc tượng thờ truyền thống.',
  109: 'Hương án có họa tiết chạm gỗ theo phong cách thời Lê, phản ánh kỹ thuật và thẩm mỹ của từng giai đoạn lịch sử.',
  110: 'Bức hoành phi “Vạn thế sư biểu” được làm năm 1888. Nội dung tên gọi tôn vinh Khổng Tử là người thầy của muôn đời.',
  111: 'Hoành phi “Cổ kim nhật nguyệt” do Nguyễn Nghiễm cho làm, thể hiện sự tôn kính đối với truyền thống học thuật.',
  112: 'Hoành phi “Cổ kim nhật nguyệt” và chuông Bích Ung được làm năm 1768.',
  113: 'Tượng thờ Khổng Tử hiện nay được làm năm 1729, thuộc giai đoạn công trình được tu bổ và hoàn thiện.',
  114: 'Tượng thờ Khổng Tử được làm bằng gỗ, phù hợp với kỹ thuật tạo tác tượng thờ truyền thống.',
  115: 'Luận ngữ ghi lại lời nói và việc làm của Khổng Tử cùng các môn đồ, là một trong những kinh điển quan trọng của Nho học.',
  116: 'Chu Văn An là nhà giáo tiêu biểu được thờ tại Văn Miếu, đại diện cho truyền thống tôn trọng người thầy và đạo học.',
  117: 'Chu Văn An được thờ tại Văn Miếu từ năm 1370, sau khi ông qua đời và được triều đình ghi nhận công lao giáo dục.',
  118: 'Chu Văn An quê ở Thanh Trì, Hà Nội. Ông nổi tiếng là một nhà giáo chính trực của triều Trần.',
  119: 'Theo truyền thuyết, người học trò của Chu Văn An là thần nước. Câu chuyện nhấn mạnh sự hy sinh để cứu dân khỏi hạn hán.',
  120: 'Chu Văn An từng dạy Thái tử Trần Vượng, người sau này là vua Trần Hiến Tông.',
  121: 'Chu Văn An giữ chức Tư nghiệp Quốc Tử Giám, vị trí gắn với việc quản lý và giảng dạy tại trường.',
  123: 'Sau khi từ quan, Chu Văn An về ở ẩn tại Chí Linh, Hải Dương. Ông tiếp tục dạy học và viết sách.',
  124: 'Tượng Chu Văn An tại khu Thái Học được làm năm 2003 trong quá trình xây dựng và hoàn thiện không gian tưởng niệm.',
  125: 'Tượng Chu Văn An tại khu Thái Học được đúc bằng đồng.',
  126: 'Tượng Chu Văn An tại khu Thái Học nặng khoảng 5 tấn, có kích thước lớn để phù hợp không gian thờ tự.',
  127: 'Tượng Chu Văn An tại khu Thái Học cao khoảng 2,3 mét.',
  128: 'Tại Văn Miếu – Quốc Tử Giám hiện thờ ba vị vua: Lý Thánh Tông, Lý Nhân Tông và Lê Thánh Tông.',
  129: 'Tượng ba vị vua ở tầng hai nhà Thái Học được làm năm 2003 trong dự án phục dựng khu Thái Học.',
  130: 'Tượng ba vị vua tại nhà Thái Học được làm bằng đồng.',
  131: 'Mỗi tượng vua tại tầng hai nhà Thái Học nặng khoảng một tấn.',
  132: 'Khu Thái Học hiện nay được xây dựng hoàn thành năm 2000 trên nền khu Quốc Tử Giám xưa.',
  133: 'Quốc Tử Giám Thăng Long hoạt động khoảng 700 năm, là trung tâm giáo dục cao nhất của nhà nước phong kiến Việt Nam.',
  134: 'Hậu đường khu Thái Học gồm hai tầng, là nơi đặt tượng thờ và giới thiệu các nhân vật lịch sử.',
  135: 'Ba vị danh nhân được thờ trên tầng hai là ba vị vua có đóng góp quan trọng cho Văn Miếu và Quốc Tử Giám.',
  136: 'Lý Thánh Tông sinh năm 1023 và là vị vua cho dựng Văn Miếu vào năm 1070.',
  137: 'Lý Thánh Tông mất năm 1072, sau thời gian trị vì có nhiều đóng góp cho giáo dục và văn hóa.',
  138: 'Lý Thánh Tông gắn với vùng Hà Nội, nơi ông cho xây dựng Văn Miếu năm 1070.',
  139: 'Lý Nhân Tông sinh năm 1066 và lên ngôi khi còn nhỏ.',
  140: 'Lý Nhân Tông mất năm 1127. Triều đại của ông gắn với khoa thi Nho học đầu tiên năm 1075.',
  141: 'Lý Nhân Tông có quê gốc ở Bắc Ninh theo dữ liệu của bộ câu hỏi.',
  142: 'Lý Nhân Tông được học tại Văn Miếu khi mới 5 tuổi, phản ánh vai trò đặc biệt của hoàng gia trong nền giáo dục thời Lý.',
  143: 'Lý Nhân Tông là người cho mở khoa thi đầu tiên trong lịch sử khoa cử Việt Nam vào năm 1075.',
  144: 'Lê Văn Thịnh đỗ đầu khoa thi năm 1075 và quê ở Bắc Ninh.',
  145: 'Lê Thánh Tông sinh năm 1442, vị vua nổi tiếng với việc phát triển giáo dục, luật pháp và khoa cử.',
  146: 'Lê Thánh Tông mất năm 1497, sau một thời kỳ trị vì thường được xem là đỉnh cao của nhà Lê sơ.',
  147: 'Bộ luật Hồng Đức, còn gọi là Quốc triều hình luật, được ban hành dưới triều Lê Thánh Tông.',
  149: 'Bác Hồ đã đến thăm Văn Miếu hai lần, thể hiện sự quan tâm đến truyền thống hiếu học và di sản giáo dục dân tộc.',
  150: 'Bác Hồ đọc hai câu thơ tặng các cụ phụ lão yêu thơ vào Tết Nguyên đán năm 1962.'
}

export function getExplanation(number: number, fallback: string): string {
  return notes[number] ?? fallback
}
